name: Release tulip

on:
  release:
    types: [published]

jobs:
  release:
    name: Release tulip
    uses: ./.github/workflows/base-release.yaml
    with:
      distribution: tulip
      goos: '[ "linux", "darwin" ]'
      goarch: '[ "amd64", "arm64" ]'
    secrets: inherit
    permissions: write-all
